# Generated by Django 3.2 on 2021-05-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productnutval'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
