# Generated by Django 3.2 on 2021-05-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productbrand_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productImage',
            new_name='ProdImage',
        ),
    ]
